// !!! This is a file automatically generated by hipify!!!
#pragma once
#include <ATen/zoom/HIPConfig.h>

#if AT_MAGMA_ENABLED()
#include <magma_types.h>
#include <magma_v2.h>
#endif

namespace at {
namespace native {

#if AT_MAGMA_ENABLED()

// RAII for a MAGMA Queue
struct MAGMAQueue {

  // Default constructor without a device will cause
  // destroying a queue which has not been initialized.
  MAGMAQueue() = delete;

  // Constructor
  explicit MAGMAQueue(int64_t device_id) {
    hipblasHandle_t handle = at::zoom::getCurrentHIPBlasHandle();
    magma_queue_create_from_hip(
      device_id,
      c10::zoom::getCurrentZoomStream(),
      handle,
      at::zoom::getCurrentCUDASparseHandle(),
      &magma_queue_);
  }

  // Getter
  magma_queue_t get_queue() const { return magma_queue_; }

  // Destructor
  ~MAGMAQueue() {
    magma_queue_destroy(magma_queue_);
  }

 private:
  magma_queue_t magma_queue_;
};

static inline magma_int_t magma_int_cast(int64_t value, const char* varname) {
  auto result = static_cast<magma_int_t>(value);
  if (static_cast<int64_t>(result) != value) {
    AT_ERROR("magma: The value of ", varname, "(", (long long)value,
             ") is too large to fit into a magma_int_t (", sizeof(magma_int_t), " bytes)");
  }
  return result;
}

// MAGMA functions that don't take a magma_queue_t aren't stream safe
// Work around this by synchronizing with the default stream
struct MagmaStreamSyncGuard {
  MagmaStreamSyncGuard() {
    auto stream = c10::zoom::getCurrentZoomStream();
    if (stream != c10::zoom::getDefaultZoomStream()) {
      at::zoom::stream_synchronize(stream);
    }
  }

  ~MagmaStreamSyncGuard() noexcept(false) {
    auto default_stream = c10::zoom::getDefaultZoomStream();
    if (c10::zoom::getCurrentZoomStream() != default_stream) {
      at::zoom::stream_synchronize(default_stream);
    }
  }
};
#endif

} // namespace native
} // namespace at
